import Footer from './components/Footer'
import NavBar from './components/NavBar'
import './globals.css'
export const metadata = {
  title: 'Incredible',
  description: 'Generated by Argile',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <NavBar />
           {children}
        </main>
          <Footer />
      </body>
    </html>
  )
}
